### ISSUE TITLE
Vertex Properties requests to Gremlin Server do not complete (Titan 1.0.0)

### ISSUE THREAD

**Issue by adurrive** [thinkaurelius/titan#1173]
Hello,

This issue is a follow up from https://github.com/jbmusso/gremlin-javascript/issues/19.

``` groovy
g.V().limit(1).properties()
```

Such requests do not complete and leave the client hanging. I have reproduced the issue with gremlin-javascript and aiogremlin (although not with the Gremlin console), using Titan 1.0.0 and the latest 1.0.1 build. The Gremlin server works as expected using TinkerGraph, which seems to indicate that the issue is related to Titan.

**Comment by spmallette** [comment]
When you used the Gremlin Console to `:remote` to Gremlin Server with Titan behind it, what configuration file did you pass to the `:remote` command?

**Comment by adurrive** [comment]
I have reproduced the issue locally with an out of the box Titan 1.0.0 using all default settings. Regarding the Gremlin console (which works) I used the default remote.yaml:

``` yaml
hosts: [localhost]
port: 8182
serializer: { className: org.apache.tinkerpop.gremlin.driver.ser.GryoMessageSerializerV1d0, config: { serializeResultToString: true }}
```
